### ISSUE TITLE
update of samples

### ISSUE THREAD

**Issue by nileio** [oxpath/oxpath-all#1]
I am exploring this project and would appreciate all help.. can we include all the samples at ospath.org in here after validating .. i am very new to it so would be great is someone can assist?
thanks

**Comment by ruslanrf** [comment]
This version of OXPath (2.0.1) has the same syntax as OXPath 2.0. We do not plan to include examples of wrappers into this repository, as web pages are subject to frequent change and it can easily make wrappers invalid.

**Comment by nileio** [comment]
Thanks for reply!I read somewhere there is a visual oxpath, as an eclipse plugin. has this plugin been built? is it part of this repo or another? couldnt figure out from the sources..

**Comment by ruslanrf** [comment]
Visual OXPath was built by the Diadem team and was used in their project. It is outdated and currently not supported, unfortunately.

To try OXPath we recommend to use http://www.oxpath.org/download/oxpath-2.0-cli.jar

**Comment by nileio** [comment]
Thanks alot for reply!
