### ISSUE TITLE
maven generate project fails

### ISSUE THREAD

**Issue by nileio** [oxpath/oxpath-all#2]
following wiki getting started page to generate a maven project fails with the error:
The desired archetype does not exist (uk.ac.ox.cs.diadem:archeoxpath:2.0)

`mvn archetype:generate -DarchetypeArtifactId=archeoxpath -DarchetypeGroupId=uk.ac.ox.cs.diadem -DarchetypeVersion=2.0 -DarchetypeRepository=http://diadem.cs.ox.ac.uk:8081/nexus/content/repositories/oxpath-public -DgroupId=org.your.company -DartifactId=project -Dpackage=org.your.company.project `-Dversion=1.0-SNAPSHOT `

> 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.4:generate (default-cli) on project standalone-pom: The desired archetype does not exist (uk.ac.ox.cs.diadem:archeoxpath:2.0) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException 

>

**Comment by ruslanrf** [comment]
Dear nileio,
To compile the current OXPath project (2.0.1), to generate all necessary jar files in your local repository, you can either use `pom.xml` in the root of the repository or pom files of each module. Please disable testing (i.e., invoke `mvn install -Dmaven.test.skip=true`).

The OXPath can be included then in your maven project with the following code:
```
<dependency>
	<groupId>org.oxpath</groupId>
	<artifactId>oxpath</artifactId>
	<version>2.0.1</version>
</dependency>
<dependency>
  <groupId>org.oxpath</groupId>
  <artifactId>environment</artifactId>
  <version>1.0.1</version>
</dependency>
<dependency>
	<groupId>org.oxpath</groupId>
	<artifactId>webapi</artifactId>
	<version>1.2.2</version>
</dependency>
```

Example of initializing the integrated web browser:
```
WebBrowserBuilder wbb = BrowserFactory
	.newBuilder(Engine.WEBDRIVER_FF)
	.disable(WebBrowser.FeatureType.PLUGINS)
	.useXvfb(wrapperInput.isXvfb())
	.useProxy(ClientUtil.createSeleniumProxy(proxy));
browser = wbb.newWebBrowser();
```

To execute a wrapper:
```
OXPath.ENGINE.evaluate(wrapper, browser, outputHandler);
```
`wrapper` is a string with an OXPath expression. `outputHandler` responsible for serializing the results of the wrapper evaluation. You can try [`XMLOutputHandler`](https://github.com/oxpath/oxpath-all/blob/master/oxpath/src/main/java/uk/ac/ox/cs/diadem/oxpath/output/XMLOutputHandler.java).

To close the web browser:
```
browser.shutdown();
```

We are planning to release a user manual with a new upcoming version of OXPath.

**Comment by nileio** [comment]
fantastic , thanks for help ! docs for the new version especially the grammar would be very useful, i am currently using the older documentation and code.
(sorry it might not be the place here to ask but is there any current forum or a channel where the development group connect for questions/information/upcoming info etc.or any plans to have one?)
suggest even the use of the wiki in here.. 
Thanks!
(compiling has given me some issues so far..)

**Comment by ruslanrf** [comment]
Github is currently the main and the only place for the OXPath development and distribution. We will consider other possibilities.

Please have a look at the paper, "OXPath: A language for scalable data extraction, automation, and crawling on the deep web", of Furche et al., Sections 1.1 and 2. It will give you some introduction into OXPath.

Provide us with an error message you receive while compiling OXPath.

**Comment by nileio** [comment]
Hi ruslan, thanks for reply.
the compilation is now successful, I had to fix a POM missing reference for 
diff_match_patch .. it was missing on oxpath module pom.
the issue though is I could not find diff_match_patch-0.0.1 jar file as referenced in pom, so I only been able to download diff_match_patch_current.jar from the internet which I think is 1.1 version. In all cases compilation was successful. Not sure if this is causing the next issue or not.

The issue is now running the generated jar with the command
`java -jar oxpath-2.0.1-cli.jar -help`

generates the following error:

`Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/collections/Predicate
	at uk.ac.ox.cs.diadem.env.configuration.ConfigurationLoader.loadDefaultTestConfiguration(ConfigurationLoader.java:278)
	at uk.ac.ox.cs.diadem.env.configuration.ConfigurationLoader.loadGlobalConfiguration(ConfigurationLoader.java:350)
	at uk.ac.ox.cs.diadem.env.configuration.ConfigurationLoader.loadInternally(ConfigurationLoader.java:547)
	at uk.ac.ox.cs.diadem.env.configuration.ConfigurationLoader.<init>(ConfigurationLoader.java:142)
	at uk.ac.ox.cs.diadem.env.configuration.ConfigurationLoader.instance(ConfigurationLoader.java:135)
	at uk.ac.ox.cs.diadem.env.configuration.ConfigurationFacility.updateConfiguration(ConfigurationFacility.java:254)
	at uk.ac.ox.cs.diadem.env.configuration.ConfigurationFacility.getConfiguration(ConfigurationFacility.java:123)
	at uk.ac.ox.cs.diadem.oxpath.core.OXPathCLI.<clinit>(OXPathCLI.java:52)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.collections.Predicate
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
`

I am looking to debug this - can you assist ?

**Comment by ruslanrf** [comment]
Hi nileio,
We do not recommend to use the client of oxpath 2.0.1. Please use [oxpath-2.0-cli](http://www.oxpath.org/download/oxpath-2.0-cli.jar) of oxpath 2.0 instead.
The current version of OXPath is mainly for the integration.

The upcoming OXPath 2.0.2 will have a client with different serialization formats for extracted data.

**Comment by nileio** [comment]
hi ruslanrf, 
does this mean that I cannot use the cli jar file which is successfully compiled on my machine ?
the jar file produced after compilation is oxpath-2.0.1-cli.jar

Is it possible to compile from source and use the cli interface ?
If not, can you elaborate a bit more please on technically why 2.0.1 would not work, whereas 2.0 would work? sorry a bit confused!
thanks

**Comment by nileio** [comment]
Thanks ruslan.. i digged up the code and I can understand what you refer to now! :)
(Note , headless bowser did not work for me , do you know if this is a known issue or a work in progress ? I am happy to open a new issue for this.

I think you may close this one

**Comment by ruslanrf** [comment]
Could you contact me please by the email "<first name>.<last name>" at Google's mail service? I hope you can decode that. :-)
