### ISSUE TITLE
AbstractJDBCOutputHandler doesn't implement waitForCompletion()

### ISSUE THREAD

**Issue by nileio** [oxpath/oxpath-all#3]
using the JDBCOutputHandler, the following exception is raised:

 

> > Exception in thread "main" uk.ac.ox.cs.diadem.oxpath.utils.OXPathRuntimeException: OXPATH: Error executing wrapper <null>. Error stacktrace <org.apache.commons.lang.NotImplementedException: waitForCompletion
> > 	at uk.ac.ox.cs.diadem.oxpath.output.OutputHandler.waitForCompletion(OutputHandler.java:91)
> > 	at uk.ac.ox.cs.diadem.oxpath.core.OXPath.invoke(OXPath.java:220)
> > 	at uk.ac.ox.cs.diadem.oxpath.core.OXPath.evaluate(OXPath.java:92)
> > 	at org.nileio.App.main(App.java:51)
> > >
> > Caused by: org.apache.commons.lang.NotImplementedException: waitForCompletion
> > 	at uk.ac.ox.cs.diadem.oxpath.output.OutputHandler.waitForCompletion(OutputHandler.java:91)
> > 	at uk.ac.ox.cs.diadem.oxpath.core.OXPath.invoke(OXPath.java:220)
> > 	at uk.ac.ox.cs.diadem.oxpath.core.OXPath.evaluate(OXPath.java:92)
> > 	... 1 more
> 
> 
> Process finished with exit code 1

On debugging this , the issue appears to be the method waitForCompletion() being
 

 ```
 public void waitForCompletion() {
    throw new NotImplementedException("waitForCompletion");
  }
```
It is requiring an override on subclass, but AbstractJDBCOutputHandler does not contain an override.

Can you please advise if this is being worked on or what is the fix ?  
I assume this was important for waiting on a data flush of some sort before resuming on.

Apparently XMLOutputHandler does not have the same issue because it has implemented a CountDownLatch.

Thanks,

**Comment by ruslanrf** [comment]
`XMLOutputHandler` does not have these issues and we suggest to use it. `AbstractJDBCOutputHandler` is an abstract class with some member functions to be implemented in its child class.

In the newer version this will be a separate maven artifact.

**Comment by nileio** [comment]
Thank you for response.. 
thank you for reply.. 
XMLOutputHandler extends AbstractCustomOutputHandler which actually has the implementation of waitForCompletion() in this instance. Therefore, I was suggesting, in the same way, that AbstractJDBCOutputHandler should also implement waitForCompletion() given that it throws an exception if no implementation exists.

**Comment by ruslanrf** [comment]
Yes, I agree, this part of the code will be improved. Thank you for identifying problems with current output handlers.
