### ISSUE TITLE
help with setting up logging

### ISSUE THREAD

**Issue by nileio** [oxpath/oxpath-all#4]
Hi ruslan,
It is been a while and I am struggling with correctly setting up logging for my client application with oxpath. I hope you can assist with this..

It appears that the call to ConfigurationFacility.getConfiguration(); somehow disables logging somewhere in the code (I cannot figure out where!). 
It once worked for me where I could see all the INFO, DEBUG log information from OXPath project in my client application console, but at some point, it just stopped working. Since then I cannot get it to print the logs into my console..

My client application is simply using the Sample java application, and my app pom is configured with following dependancy
```
 <dependency>
          <groupId>org.slf4j</groupId>
          <artifactId>slf4j-log4j12</artifactId>
          <version>1.7.22</version>
      </dependency>
```

The app code is simply:

```
public static void main(final String[] args) throws ClassNotFoundException, SQLException, InterruptedException {
        // configure logging
        final Logger logger = LoggerFactory.getLogger(App.class);
        logger.info("Starting App...");
        ConfigurationFacility.getConfiguration();
        // instantiate a browser mozilla
        logger.info("Instantiate browser");
        final WebBrowser browser = BrowserFactory.newBuilder(Engine.WEBDRIVER_FF).disable(WebBrowser.FeatureType.PLUGINS)
                .useXvfb(false).newWebBrowser();
        try {

            final XMLConfiguration dbConfiguration = new XMLConfiguration("config.xml");
```

I do not get any logging information from oxpath project (which is loaded on my IDE) .
appreciate it if you can assist or give me a hint where could the problem be ?

**Comment by ruslanrf** [comment]
Hi Sam,
Your code looks correct. I will check this case for the upcoming version of OXPath.

Currently, I would suggest you to try the VM argument `-DLOG_CONFIG_LOADER="debug"`.
Furthermore, you can try something like that:
```
Configuration conf = ConfigurationFacility.getConfiguration();
ConfigurationFacility.addOptionalConfiguration(this.getClass().getResource(YOUR_LOG_PROPERTY_FILE));
```
In the POM file, you can add the full stack of logging libraries:
```
<dependency>
  <groupId>log4j</groupId>
  <artifactId>log4j</artifactId>
  <version>1.2.17</version>
</dependency>
<dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-api</artifactId>
  <version>1.7.5</version>
</dependency>
<dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-log4j12</artifactId>
</dependency>
```

Hopefully, it will help.

**Comment by nileio** [comment]
Thanks for your reply rslan.. for the time being , I have modified the oxpath code to enable debug forcibly through a static field assignment (as a workaround for now!!).. 
I will try your solution and come back to you with results.

**Comment by nileio** [comment]
Hi Rslan,
Just as an update 
using the VM parameter `-DLOG_CONFIG_LOADER="debug"` works, and then the console prints out logs from the project.

the trial to load my own log4j properties as optional configuration file fail with the following error:
```
[Fatal Error] log4j.properties:1:1: Content is not allowed in prolog.
Exception in thread "main" uk.ac.ox.cs.diadem.env.configuration.InvalidFileConfigurationRuntimeException: Failed loading optional configuration 
```
thanks

**Comment by ruslanrf** [comment]
The problem is in your configuration file, please send me your example.
