### ISSUE TITLE
RDFOutputHandler hung on waiting for completion

### ISSUE THREAD

**Issue by nileio** [oxpath/oxpath-all#6]
Hi Rslan,
Not sure if this issue is known, but I thought to log it for hopefully possible fix in next release.

```
final RDFOutputHandler rdfHandler = new RDFOutputHandler(rdfConfiguration);
....
// invoke OXPath
            final OXPathType evaluate = OXPath.ENGINE.evaluate(in, browser, rdfHandler);
----
// prints the model on console
            System.out.println(rdfHandler.returnModelAsString());
```
causes the following issue
 
```
[INFO] AbstractCustomOutputHandler:: <'UNKNOWN_ID'> : Waiting 10 seconds for completion on the output handler
[INFO] AbstractCustomOutputHandler:: <'UNKNOWN_ID'> : Waiting 10 seconds for completion on the output handler
[INFO] AbstractCustomOutputHandler:: <'UNKNOWN_ID'> : Waiting 10 seconds for completion on the output handler
[INFO] AbstractCustomOutputHandler:: <'UNKNOWN_ID'> : Waiting 10 seconds for completion on the output handler
```

Note: tried the RDFHandler from the command line using oxpath-cli and it works as expected.

Thanks

**Comment by ruslanrf** [comment]
Hi Sam,

This OXPath version is mainly what has been extracted from Diadem's sources code repository. RDF output handler will be removed form the OXPath core. However, it can be added later as a separate maven artifact for converting the OXPath extraction tree into RDF.
